### ISSUE TITLE
update BackwardEuler to support simplified-SDC

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Microphysics#1033]
At the moment, only VODE supports simplified-SDC.  It should be straightforward to update the BackwardEuler solver to support simplified-SDC.

**Comment by aisclark91** [comment]
I will like to try implementing this feature. I know Max has been working hard in this, however I think it would be an amazing opportunity to test what I have learned so far and contribute here.

**Comment by zingale** [comment]
this is now completed #1042
