### ISSUE TITLE
Rate tabulation inconsistencies in aprox19, aprox21, iso7

### ISSUE THREAD

**Issue by yut23** [AMReX-Astro/Microphysics#1124]
Several rates in aprox19, aprox21, and iso7 have `data.rate_can_be_tabulated = 1` by default, but don't have any code in `evaluate_analytical_rate`:

| rate | networks |
| --- | --- |
| `Fe52_2N_to_Fe54` | aprox19, aprox21 |
| `Fe52_He4_to_Fe54_2P` | aprox19, aprox21 |
| `Fe54_2P_to_Ni56` | aprox19, aprox21 |
| `Fe54_2N_to_Fe56` | aprox21 |
| `Fe54_He4_to_Fe56_2P` | aprox21 |
|` Si28_7He4_to_Ni56` | iso7 |

These rates are all handled later in `postprocess_rate`, but the outputs of `evaluate_analytical_rate` are put directly into the rate tabulation arrays in `tabulate_rates`, leading to uninitialized memory errors without #1123.

Additionally, `He3_He3_to_He4_2P` is defined but never used in aprox19 and aprox21 (it looks like `He3_He3_to_He4_2H1` was used instead).

**Comment by maxpkatz** [comment]
Yeah, I guess it doesn't make much sense for a rate that depends on other rates to be eligible for tabulation. I'm not sure what I was thinking there.
