### ISSUE TITLE
Uninitialized variables in eos_t

### ISSUE THREAD

**Issue by yut23** [AMReX-Astro/Microphysics#1130]
Several of the EOS implementations never initialize some of the variables in `eos_t` (that they presumably don't use), which is causing the two remaining `test_eos` failures in the test suite.

  | multigamma | polytrope | rad_power_law | tillotson | ztwd
-- | :--: | :--: | :--: | :--: | :--:
s |   | ✗ |   |   | ✗
dpdT |   |   | ✗ |   |  
dedT |   |   | ✗ |   |  
dedr |   |   | ✗ |   |  
dhdT |   |   | ✗ | ✗ |  
dhdr |   |   | ✗ | ✗ |  
dsdT |   |   | ✗ | ✗ |  
dsdr |   |   | ✗ | ✗ |  
dpde |   |   | ✗ |   |  
dpdr_e |   |   | ✗ |   |  
cp |   |   | ✗ |   |  
xne | ✗ | ✗ | ✗ | ✗ | ✗
xnp | ✗ | ✗ | ✗ | ✗ | ✗
eta | ✗ | ✗ | ✗ | ✗ | ✗
pele | ✗ | ✗ | ✗ | ✗ | ✗
ppos | ✗ | ✗ | ✗ | ✗ | ✗
mu | ✗ | ✗ | ✗ | ✗ | ✗
dpdA |   |   | ✗ | ✗ |  
dpdZ |   |   | ✗ | ✗ |  
dedA |   |   | ✗ | ✗ |  
dedZ |   |   | ✗ | ✗ |

**Comment by zingale** [comment]
perhaps we should initialize these all in the struct itself?
