### ISSUE TITLE
remove abort_on_failure

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Microphysics#1173]
At the moment, if `abort_on_failure` is set, we abort if the burn fails, but _only on CPUs_.  If the burn is done on the GPU, then we don't.  We should instead move this up to the application code, and make it responsible for checking the return code `burn_t.success`.  

Castro already does this
MAESTROeX will once https://github.com/AMReX-Astro/MAESTROeX/pull/379 is merged
I am not sure about Quokka (@psharda?)

**Comment by psharda** [comment]
Hi @zingale, yes, this is what we are doing in Quokka: we use `burn_t.success` to evaluate if integration in microphysics was successful, and this way it works both for CPUs and GPUs: https://github.com/quokka-astro/quokka/blob/development/src/Chemistry.hpp#L83
