### ISSUE TITLE
treat compiler warnings as errors

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Astro/Microphysics#1184]
There are a few compiler warnings that are causing the Quokka CI to fail, since we have now enabled treating warnings as errors in our builds (`-Werror -Wall -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -Wno-strict-aliasing`).

Is this something that can be enabled for Microphysics builds?

**Comment by zingale** [comment]
yeah, I think it's a good idea.

**Comment by BenWibking** [comment]
@psharda can you add this to the CMake build? all it requires is:
```
add_compile_options(-Werror -Wall -Wextra -Wno-unused-parameter -Wno-unknown-pragmas -Wno-strict-aliasing)
```

**Comment by zingale** [comment]
I think this is fixed now
