### ISSUE TITLE
avoid "using namespace" in headers included by application codes

### ISSUE THREAD

**Issue by BenWibking** [AMReX-Astro/Microphysics#1406]
This breaks HIP builds, since some ROCm headers have "detail" namespaces at global scope (which is bad practice of them!) that then conflict with "amrex::detail".

More generally, it violates the C++ Core Guidelines: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf7-dont-write-using-namespace-at-global-scope-in-a-header-file

Unfortunately, "using namespace amrex" is currently used in a lot of headers: https://github.com/search?q=repo%3AAMReX-Astro%2FMicrophysics+%22using+namespace+amrex%22&type=code

**Comment by zingale** [comment]
this has been largely fixed.
