### ISSUE TITLE
use improved screening of Chugunov et al. 2007

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Microphysics#146]
Sam Jones recommends this screening formulation:

https://journals.aps.org/prd/abstract/10.1103/PhysRevD.76.025028

It is a fit to the screening that also gives the bounds of where it is applicable.

**Comment by dwillcox** [comment]
We'll incorporate this with a `SCREEN_DIR` preprocessor variable.

**Comment by dwillcox** [comment]
Attaching a screening module from Sam Jones for this ...

[screening_chugunov.F90.txt](https://github.com/starkiller-astro/Microphysics/files/2665602/screening_chugunov.F90.txt)

**Comment by zingale** [comment]
We should look at MESA -- they are using the same routine and may have made some improvements.

**Comment by KiranEiden** [comment]
It appears that Chugonov and DeWitt released a [second paper](https://arxiv.org/abs/0905.3844) two years later extending this from OCPs to binary ionic mixtures, which may offer some additional insight. The extension from OCPs to ionic mixtures in Sam Jones' implementation was based on work by [Itoh et al.](http://adsabs.harvard.edu/abs/1979ApJ...234.1079I)

**Comment by KiranEiden** [comment]
MESA's implementation uses slightly different formulas for the Coulomb coupling parameter and plasma frequency. They replace Zbar**(1/3) in the coupling parameter by (a1 + a2) / 2,  and Zbar**2 with Z1 * Z2 in the plasma frequency.

**Comment by KiranEiden** [comment]
I wrote up a Python implementation of both the Chugunov 2007 and Chugunov 2009 screening in pynucastro when I was working at LBL a few years ago. The code is in [this file](https://github.com/pynucastro/pynucastro/blob/screening/pynucastro/rates/rate.py) (lines 1164-1409) -- it hasn't been merged in with the main/development branches. I think the Chugunov 2009 function is still incomplete.

There are a few spots where it differs from MESA's implementation, and I think it might be slightly different from Sam's implementation as well. Not sure if it will end up being helpful or not to someone trying to implement this, but I thought it might be worth sharing.

**Comment by zingale** [comment]
@yut23 will work on this
