### ISSUE TITLE
sync self-consistent NSE update with tabular NSE

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Microphysics#1543]
In `nse_update_sdc.H`, the tabular NSE has been written up in the SDC+NSE paper and was shown to be 2nd order.  We should sync the self-consistent NSE up with it.

**Comment by zhichen3** [comment]
In `nse_derivs` we need the derivatives to calculate energies. And if we were to do the same, we will need Ydots if we calculate energy using `e_nuc = -N_A * c^2 * dY_k/dt * m_k`.  So do I just call the rhs for it?

Also what if we carry the mass / molar fraction of the previous timestep and do a central difference do get the derivative?

**Comment by zingale** [comment]
we only want the energy from the weak reaction rates, not everything.  So I think that we should add a function to pynucastro nets that evaluates just the energy from weak rates.  We will need to call the tables each time, but it should not be too bad.

**Comment by zhichen3** [comment]
just to reiterate, so we want to do `e_nuc = -N_A * c^2 * dY_k/dt * m_k`. But using only weak rate contributions in `dY_k/dt` because in NSE, strong reactions should balance out and only weak reactions contribute. Then we do the same RK2 procedure in Tabular NSE.

**Comment by zingale** [comment]
Yes.  That's my thinking
