### ISSUE TITLE
time and temp_start not properly output after burn failure on Frontier GPU

### ISSUE THREAD

**Issue by brady-ryan** [AMReX-Astro/Microphysics#1630]
When running subch_planar with GPUs on Frontier, the time and temp_start of a failed burn state does not seem to be properly stored. Here is an example output:

`[ERROR] integration failed in net, istate = -6, time = 0, dt = 7.54401e-07, dens_start = 1.87438e+06, temp_start = 0`

**Comment by yut23** [comment]
I'm not sure about the time, but `state_save.T_in` is indeed only set on CPU: https://github.com/AMReX-Astro/Microphysics/blob/ecbc595ec086227d1120b97efc51d92aa6e14dc4/integration/integrator_setup_sdc.H#L115-L120 https://github.com/AMReX-Astro/Microphysics/blob/ecbc595ec086227d1120b97efc51d92aa6e14dc4/integration/integrator_setup_strang.H#L105-L110

**Comment by zingale** [comment]
this is fixed by #1635 
I don't think there's an issue with time -- if I run `burn_cell_sdc` on GPUs and force it to fail by giving it a hard burn, then I get the expected intermediary time.
