### ISSUE TITLE
remove temporary spec_jac for auto jacobians

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Microphysics#701]
In the new way of automatically computing the species Jacobians we have a temporary array `spec_jac` that we will and then we copy it into the main `jac` array to pass out.  We should eliminate this temporary.

**Comment by maxpkatz** [comment]
Closing as resolved -- there is only a single Jacobian array now in the `jac()` that's in `rhs.H` and it's computed on a term-by-term basis.
