### ISSUE TITLE
allow retry with different Jacobian

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Microphysics#943]
The analytic Jacobian often works really well, but for some hard burns, the numerical Jacobian is better.  In this case, rather than failing and having to have the code (Castro) throw away the entire timestep and retry, it would be useful to allow for the whole burn for a zone to be retried with the numerical Jacobian.

This kinda brings back the retry mechanism we had in VODE a while back, but in a slightly different fashion.

**Comment by maxpkatz** [comment]
Another angle here would be to retry an individual burning step with the other Jacobian. It is probably easier to implement the first idea because we have already done something similar, but it's worth pursuing the within-burn retries because it's probably significantly cheaper.

**Comment by maxpkatz** [comment]
The prerequisite for either idea is that the interfaces in the burner going down to dvjac need to decide which Jacobian to use via function arguments rather than reading the `integrator.jacobian` runtime parameter.

**Comment by zingale** [comment]
ah indeed, so maybe the first step is to just do that refactor

**Comment by zingale** [comment]
my read of this is that is NFLAG < 0, then we had a failure (singular, or convergence failure), and we should redo the Jacobian, perhaps switching to numerical from analytic.

but perhaps these say the same thing, since ICF and NFLAG seem to be related.

**Comment by zingale** [comment]
Ah, okay, I understand now.  Only `ICF` makes it out of `dvnlsd`, so indeed, if we force a change of Jacobian type in `dvjac` when `ICF > 0`, then I think that will accomplish our goals -- that will only change the type if there was a failure, and not if the Jacobian is "stale" because of the caching.

**Comment by zingale** [comment]
we should also consider the idea of not integrating T on retry

**Comment by zingale** [comment]
we now do a retry after the entire integration fail, instead of internal to the ODE solver.  That seems to work well for now.
