### ISSUE TITLE
allow for multiple networks

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Microphysics#99]
It would be nice to have two different reaction networks built in and be able to chose which net we use in a zone based on thermodynamic conditions.

E.g., for a sub-Ch simulation, have a He burning net (like subch) and also a carbon-burning net, and use the He burning net in the He layer and the carbon burning once we ignite the core.

**Comment by maxpkatz** [comment]
An alternative is to employ a mask that determines which species of a network we are currently integrating.

**Comment by maxpkatz** [comment]
If we wanted to use the mask and also make it automated, perhaps we could specify some tolerance levels below which a given isotope is automatically not integrated (e.g. X < 1.0e-4).
