### ISSUE TITLE
consider SciPy BDF solver as alternative to VODE

### ISSUE THREAD

**Issue by zingale** [AMReX-Astro/Microphysics#994]
The SciPy BDF solver looks quite clean and is implemented completely in python:
https://github.com/scipy/scipy/blob/main/scipy/integrate/_ivp/bdf.py

in the pynucastro comparisons, this seemed to perform well compared to VODE, and might make for a good alternative

**Comment by psharda** [comment]
+1 for this idea. BDF works well for the primordial_chem stuff too.

**Comment by zingale** [comment]
note that that is what VODE is -- it is BDF.  It is just a different implementation.

**Comment by zingale** [comment]
closing this in favor of the new RKC integrator we are experimenting with now
